services:
  - type: web
    name: lapaz-store
    runtime: python
    pythonVersion: 3.12.3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
