services:
  - type: web
    name: lapaz-store
    runtime: python
    # Render supports several versions of Python. This project targets Python 3.11
    # to avoid compatibility issues with certain dependencies.
    pythonVersion: 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
