services:
  - type: web
    name: la-paz-store
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: uploads